/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_PBRT_PROTOBUF_PBRT_PB_H_INCLUDED
#define PB_PBRT_PROTOBUF_PBRT_PB_H_INCLUDED
#include "nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _pbrt_protobuf_Manifest {
    pb_callback_t objects;
} pbrt_protobuf_Manifest;

typedef struct _pbrt_protobuf_Matrix {
    pb_callback_t m;
} pbrt_protobuf_Matrix;

typedef struct _pbrt_protobuf_ParamSet {
    pb_callback_t bools;
    pb_callback_t ints;
    pb_callback_t floats;
    pb_callback_t point2fs;
    pb_callback_t vector2fs;
    pb_callback_t point3fs;
    pb_callback_t vector3fs;
    pb_callback_t normals;
    pb_callback_t spectra;
    pb_callback_t strings;
    pb_callback_t textures;
} pbrt_protobuf_ParamSet;

typedef struct _pbrt_protobuf_ParamSet_ItemBool {
    pb_callback_t name;
    pb_callback_t values;
} pbrt_protobuf_ParamSet_ItemBool;

typedef struct _pbrt_protobuf_ParamSet_ItemFloat {
    pb_callback_t name;
    pb_callback_t values;
} pbrt_protobuf_ParamSet_ItemFloat;

typedef struct _pbrt_protobuf_ParamSet_ItemInt {
    pb_callback_t name;
    pb_callback_t values;
} pbrt_protobuf_ParamSet_ItemInt;

typedef struct _pbrt_protobuf_ParamSet_ItemNormal3f {
    pb_callback_t name;
    pb_callback_t values;
} pbrt_protobuf_ParamSet_ItemNormal3f;

typedef struct _pbrt_protobuf_ParamSet_ItemPoint2f {
    pb_callback_t name;
    pb_callback_t values;
} pbrt_protobuf_ParamSet_ItemPoint2f;

typedef struct _pbrt_protobuf_ParamSet_ItemPoint3f {
    pb_callback_t name;
    pb_callback_t values;
} pbrt_protobuf_ParamSet_ItemPoint3f;

typedef struct _pbrt_protobuf_ParamSet_ItemSpectrum {
    pb_callback_t name;
    pb_callback_t values;
} pbrt_protobuf_ParamSet_ItemSpectrum;

typedef struct _pbrt_protobuf_ParamSet_ItemString {
    pb_callback_t name;
    pb_callback_t values;
} pbrt_protobuf_ParamSet_ItemString;

typedef struct _pbrt_protobuf_ParamSet_ItemVector2f {
    pb_callback_t name;
    pb_callback_t values;
} pbrt_protobuf_ParamSet_ItemVector2f;

typedef struct _pbrt_protobuf_ParamSet_ItemVector3f {
    pb_callback_t name;
    pb_callback_t values;
} pbrt_protobuf_ParamSet_ItemVector3f;

typedef struct _pbrt_protobuf_RGBSpectrum {
    pb_callback_t c;
} pbrt_protobuf_RGBSpectrum;

typedef struct _pbrt_protobuf_AnimatedTransform {
    bool has_start_transform;
    pbrt_protobuf_Matrix start_transform;
    bool has_end_transform;
    pbrt_protobuf_Matrix end_transform;
    float start_time;
    float end_time;
} pbrt_protobuf_AnimatedTransform;

typedef struct _pbrt_protobuf_Camera_Film_Filter {
    pb_callback_t name;
    bool has_paramset;
    pbrt_protobuf_ParamSet paramset;
} pbrt_protobuf_Camera_Film_Filter;

typedef struct _pbrt_protobuf_Light {
    pb_callback_t name;
    bool has_paramset;
    pbrt_protobuf_ParamSet paramset;
    bool has_light_to_world;
    pbrt_protobuf_Matrix light_to_world;
} pbrt_protobuf_Light;

typedef struct _pbrt_protobuf_Normal3f {
    float x;
    float y;
    float z;
} pbrt_protobuf_Normal3f;

typedef struct _pbrt_protobuf_ObjectKey {
    uint32_t type;
    uint64_t id;
} pbrt_protobuf_ObjectKey;

typedef struct _pbrt_protobuf_Point2f {
    float x;
    float y;
} pbrt_protobuf_Point2f;

typedef struct _pbrt_protobuf_Point2i {
    int32_t x;
    int32_t y;
} pbrt_protobuf_Point2i;

typedef struct _pbrt_protobuf_Point3f {
    float x;
    float y;
    float z;
} pbrt_protobuf_Point3f;

typedef struct _pbrt_protobuf_TextureParams {
    bool has_geom_params;
    pbrt_protobuf_ParamSet geom_params;
    bool has_material_params;
    pbrt_protobuf_ParamSet material_params;
    pb_callback_t float_textures;
    pb_callback_t spectrum_textures;
} pbrt_protobuf_TextureParams;

typedef struct _pbrt_protobuf_TextureParams_FloatTexturesEntry {
    pb_callback_t key;
    int32_t value;
} pbrt_protobuf_TextureParams_FloatTexturesEntry;

typedef struct _pbrt_protobuf_TextureParams_SpectrumTexturesEntry {
    pb_callback_t key;
    int32_t value;
} pbrt_protobuf_TextureParams_SpectrumTexturesEntry;

typedef struct _pbrt_protobuf_Triangle {
    int64_t mesh_id;
    int64_t tri_number;
} pbrt_protobuf_Triangle;

typedef struct _pbrt_protobuf_TriangleMesh {
    int32_t n_triangles;
    int32_t n_vertices;
    pb_callback_t vertex_indices;
    pb_callback_t p;
    pb_callback_t n;
    pb_callback_t s;
    pb_callback_t uv;
    int64_t material_id;
    int64_t id;
} pbrt_protobuf_TriangleMesh;

typedef struct _pbrt_protobuf_Vector2f {
    float x;
    float y;
} pbrt_protobuf_Vector2f;

typedef struct _pbrt_protobuf_Vector3f {
    float x;
    float y;
    float z;
} pbrt_protobuf_Vector3f;

typedef struct _pbrt_protobuf_Bounds2f {
    bool has_point_min;
    pbrt_protobuf_Point2f point_min;
    bool has_point_max;
    pbrt_protobuf_Point2f point_max;
} pbrt_protobuf_Bounds2f;

typedef struct _pbrt_protobuf_Bounds2i {
    bool has_point_min;
    pbrt_protobuf_Point2i point_min;
    bool has_point_max;
    pbrt_protobuf_Point2i point_max;
} pbrt_protobuf_Bounds2i;

typedef struct _pbrt_protobuf_Bounds3f {
    bool has_point_min;
    pbrt_protobuf_Point3f point_min;
    bool has_point_max;
    pbrt_protobuf_Point3f point_max;
} pbrt_protobuf_Bounds3f;

typedef struct _pbrt_protobuf_Camera_Film {
    pb_callback_t name;
    bool has_paramset;
    pbrt_protobuf_ParamSet paramset;
    bool has_filter;
    pbrt_protobuf_Camera_Film_Filter filter;
} pbrt_protobuf_Camera_Film;

typedef struct _pbrt_protobuf_FloatTexture {
    pb_callback_t name;
    bool has_tex2world;
    pbrt_protobuf_Matrix tex2world;
    bool has_texture_params;
    pbrt_protobuf_TextureParams texture_params;
} pbrt_protobuf_FloatTexture;

typedef struct _pbrt_protobuf_Manifest_Object {
    bool has_id;
    pbrt_protobuf_ObjectKey id;
    pb_callback_t dependencies;
    uint64_t size;
} pbrt_protobuf_Manifest_Object;

typedef struct _pbrt_protobuf_Material {
    pb_callback_t name;
    bool has_texture_params;
    pbrt_protobuf_TextureParams texture_params;
} pbrt_protobuf_Material;

typedef struct _pbrt_protobuf_SampleData {
    bool has_p_film;
    pbrt_protobuf_Point2f p_film;
    float weight;
} pbrt_protobuf_SampleData;

typedef struct _pbrt_protobuf_SpectrumTexture {
    pb_callback_t name;
    bool has_tex2world;
    pbrt_protobuf_Matrix tex2world;
    bool has_texture_params;
    pbrt_protobuf_TextureParams texture_params;
} pbrt_protobuf_SpectrumTexture;

typedef struct _pbrt_protobuf_TransformedPrimitive {
    bool has_transform;
    pbrt_protobuf_AnimatedTransform transform;
    int64_t root_ref;
} pbrt_protobuf_TransformedPrimitive;

typedef struct _pbrt_protobuf_BVHNode {
    bool has_bounds;
    pbrt_protobuf_Bounds3f bounds;
    int64_t left_ref;
    int64_t right_ref;
    uint32_t axis;
    pb_callback_t transformed_primitives;
    pb_callback_t triangles;
} pbrt_protobuf_BVHNode;

typedef struct _pbrt_protobuf_Camera {
    pb_callback_t name;
    bool has_paramset;
    pbrt_protobuf_ParamSet paramset;
    bool has_camera_to_world;
    pbrt_protobuf_AnimatedTransform camera_to_world;
    bool has_film;
    pbrt_protobuf_Camera_Film film;
} pbrt_protobuf_Camera;

typedef struct _pbrt_protobuf_Sampler {
    pb_callback_t name;
    bool has_paramset;
    pbrt_protobuf_ParamSet paramset;
    bool has_sample_bounds;
    pbrt_protobuf_Bounds2i sample_bounds;
} pbrt_protobuf_Sampler;

typedef struct _pbrt_protobuf_Scene {
    bool has_world_bound;
    pbrt_protobuf_Bounds3f world_bound;
} pbrt_protobuf_Scene;


/* Initializer values for message structs */
#define pbrt_protobuf_Point2f_init_default       {0, 0}
#define pbrt_protobuf_Point2i_init_default       {0, 0}
#define pbrt_protobuf_Point3f_init_default       {0, 0, 0}
#define pbrt_protobuf_Vector2f_init_default      {0, 0}
#define pbrt_protobuf_Vector3f_init_default      {0, 0, 0}
#define pbrt_protobuf_Normal3f_init_default      {0, 0, 0}
#define pbrt_protobuf_Matrix_init_default        {{{NULL}, NULL}}
#define pbrt_protobuf_AnimatedTransform_init_default {false, pbrt_protobuf_Matrix_init_default, false, pbrt_protobuf_Matrix_init_default, 0, 0}
#define pbrt_protobuf_Bounds2i_init_default      {false, pbrt_protobuf_Point2i_init_default, false, pbrt_protobuf_Point2i_init_default}
#define pbrt_protobuf_Bounds2f_init_default      {false, pbrt_protobuf_Point2f_init_default, false, pbrt_protobuf_Point2f_init_default}
#define pbrt_protobuf_Bounds3f_init_default      {false, pbrt_protobuf_Point3f_init_default, false, pbrt_protobuf_Point3f_init_default}
#define pbrt_protobuf_TransformedPrimitive_init_default {false, pbrt_protobuf_AnimatedTransform_init_default, 0}
#define pbrt_protobuf_TriangleMesh_init_default  {0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define pbrt_protobuf_Triangle_init_default      {0, 0}
#define pbrt_protobuf_BVHNode_init_default       {false, pbrt_protobuf_Bounds3f_init_default, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_RGBSpectrum_init_default   {{{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemBool_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemInt_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemFloat_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemPoint2f_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemVector2f_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemPoint3f_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemVector3f_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemNormal3f_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemSpectrum_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemString_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_Sampler_init_default       {{{NULL}, NULL}, false, pbrt_protobuf_ParamSet_init_default, false, pbrt_protobuf_Bounds2i_init_default}
#define pbrt_protobuf_Light_init_default         {{{NULL}, NULL}, false, pbrt_protobuf_ParamSet_init_default, false, pbrt_protobuf_Matrix_init_default}
#define pbrt_protobuf_Camera_init_default        {{{NULL}, NULL}, false, pbrt_protobuf_ParamSet_init_default, false, pbrt_protobuf_AnimatedTransform_init_default, false, pbrt_protobuf_Camera_Film_init_default}
#define pbrt_protobuf_Camera_Film_init_default   {{{NULL}, NULL}, false, pbrt_protobuf_ParamSet_init_default, false, pbrt_protobuf_Camera_Film_Filter_init_default}
#define pbrt_protobuf_Camera_Film_Filter_init_default {{{NULL}, NULL}, false, pbrt_protobuf_ParamSet_init_default}
#define pbrt_protobuf_SampleData_init_default    {false, pbrt_protobuf_Point2f_init_default, 0}
#define pbrt_protobuf_Scene_init_default         {false, pbrt_protobuf_Bounds3f_init_default}
#define pbrt_protobuf_ObjectKey_init_default     {0, 0}
#define pbrt_protobuf_TextureParams_init_default {false, pbrt_protobuf_ParamSet_init_default, false, pbrt_protobuf_ParamSet_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_TextureParams_FloatTexturesEntry_init_default {{{NULL}, NULL}, 0}
#define pbrt_protobuf_TextureParams_SpectrumTexturesEntry_init_default {{{NULL}, NULL}, 0}
#define pbrt_protobuf_Material_init_default      {{{NULL}, NULL}, false, pbrt_protobuf_TextureParams_init_default}
#define pbrt_protobuf_FloatTexture_init_default  {{{NULL}, NULL}, false, pbrt_protobuf_Matrix_init_default, false, pbrt_protobuf_TextureParams_init_default}
#define pbrt_protobuf_SpectrumTexture_init_default {{{NULL}, NULL}, false, pbrt_protobuf_Matrix_init_default, false, pbrt_protobuf_TextureParams_init_default}
#define pbrt_protobuf_Manifest_init_default      {{{NULL}, NULL}}
#define pbrt_protobuf_Manifest_Object_init_default {false, pbrt_protobuf_ObjectKey_init_default, {{NULL}, NULL}, 0}
#define pbrt_protobuf_Point2f_init_zero          {0, 0}
#define pbrt_protobuf_Point2i_init_zero          {0, 0}
#define pbrt_protobuf_Point3f_init_zero          {0, 0, 0}
#define pbrt_protobuf_Vector2f_init_zero         {0, 0}
#define pbrt_protobuf_Vector3f_init_zero         {0, 0, 0}
#define pbrt_protobuf_Normal3f_init_zero         {0, 0, 0}
#define pbrt_protobuf_Matrix_init_zero           {{{NULL}, NULL}}
#define pbrt_protobuf_AnimatedTransform_init_zero {false, pbrt_protobuf_Matrix_init_zero, false, pbrt_protobuf_Matrix_init_zero, 0, 0}
#define pbrt_protobuf_Bounds2i_init_zero         {false, pbrt_protobuf_Point2i_init_zero, false, pbrt_protobuf_Point2i_init_zero}
#define pbrt_protobuf_Bounds2f_init_zero         {false, pbrt_protobuf_Point2f_init_zero, false, pbrt_protobuf_Point2f_init_zero}
#define pbrt_protobuf_Bounds3f_init_zero         {false, pbrt_protobuf_Point3f_init_zero, false, pbrt_protobuf_Point3f_init_zero}
#define pbrt_protobuf_TransformedPrimitive_init_zero {false, pbrt_protobuf_AnimatedTransform_init_zero, 0}
#define pbrt_protobuf_TriangleMesh_init_zero     {0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define pbrt_protobuf_Triangle_init_zero         {0, 0}
#define pbrt_protobuf_BVHNode_init_zero          {false, pbrt_protobuf_Bounds3f_init_zero, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_RGBSpectrum_init_zero      {{{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemBool_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemInt_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemFloat_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemPoint2f_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemVector2f_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemPoint3f_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemVector3f_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemNormal3f_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemSpectrum_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_ParamSet_ItemString_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_Sampler_init_zero          {{{NULL}, NULL}, false, pbrt_protobuf_ParamSet_init_zero, false, pbrt_protobuf_Bounds2i_init_zero}
#define pbrt_protobuf_Light_init_zero            {{{NULL}, NULL}, false, pbrt_protobuf_ParamSet_init_zero, false, pbrt_protobuf_Matrix_init_zero}
#define pbrt_protobuf_Camera_init_zero           {{{NULL}, NULL}, false, pbrt_protobuf_ParamSet_init_zero, false, pbrt_protobuf_AnimatedTransform_init_zero, false, pbrt_protobuf_Camera_Film_init_zero}
#define pbrt_protobuf_Camera_Film_init_zero      {{{NULL}, NULL}, false, pbrt_protobuf_ParamSet_init_zero, false, pbrt_protobuf_Camera_Film_Filter_init_zero}
#define pbrt_protobuf_Camera_Film_Filter_init_zero {{{NULL}, NULL}, false, pbrt_protobuf_ParamSet_init_zero}
#define pbrt_protobuf_SampleData_init_zero       {false, pbrt_protobuf_Point2f_init_zero, 0}
#define pbrt_protobuf_Scene_init_zero            {false, pbrt_protobuf_Bounds3f_init_zero}
#define pbrt_protobuf_ObjectKey_init_zero        {0, 0}
#define pbrt_protobuf_TextureParams_init_zero    {false, pbrt_protobuf_ParamSet_init_zero, false, pbrt_protobuf_ParamSet_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define pbrt_protobuf_TextureParams_FloatTexturesEntry_init_zero {{{NULL}, NULL}, 0}
#define pbrt_protobuf_TextureParams_SpectrumTexturesEntry_init_zero {{{NULL}, NULL}, 0}
#define pbrt_protobuf_Material_init_zero         {{{NULL}, NULL}, false, pbrt_protobuf_TextureParams_init_zero}
#define pbrt_protobuf_FloatTexture_init_zero     {{{NULL}, NULL}, false, pbrt_protobuf_Matrix_init_zero, false, pbrt_protobuf_TextureParams_init_zero}
#define pbrt_protobuf_SpectrumTexture_init_zero  {{{NULL}, NULL}, false, pbrt_protobuf_Matrix_init_zero, false, pbrt_protobuf_TextureParams_init_zero}
#define pbrt_protobuf_Manifest_init_zero         {{{NULL}, NULL}}
#define pbrt_protobuf_Manifest_Object_init_zero  {false, pbrt_protobuf_ObjectKey_init_zero, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define pbrt_protobuf_Manifest_objects_tag       1
#define pbrt_protobuf_Matrix_m_tag               1
#define pbrt_protobuf_ParamSet_bools_tag         1
#define pbrt_protobuf_ParamSet_ints_tag          2
#define pbrt_protobuf_ParamSet_floats_tag        3
#define pbrt_protobuf_ParamSet_point2fs_tag      4
#define pbrt_protobuf_ParamSet_vector2fs_tag     5
#define pbrt_protobuf_ParamSet_point3fs_tag      6
#define pbrt_protobuf_ParamSet_vector3fs_tag     7
#define pbrt_protobuf_ParamSet_normals_tag       8
#define pbrt_protobuf_ParamSet_spectra_tag       9
#define pbrt_protobuf_ParamSet_strings_tag       10
#define pbrt_protobuf_ParamSet_textures_tag      11
#define pbrt_protobuf_ParamSet_ItemBool_name_tag 1
#define pbrt_protobuf_ParamSet_ItemBool_values_tag 2
#define pbrt_protobuf_ParamSet_ItemFloat_name_tag 1
#define pbrt_protobuf_ParamSet_ItemFloat_values_tag 2
#define pbrt_protobuf_ParamSet_ItemInt_name_tag  1
#define pbrt_protobuf_ParamSet_ItemInt_values_tag 2
#define pbrt_protobuf_ParamSet_ItemNormal3f_name_tag 1
#define pbrt_protobuf_ParamSet_ItemNormal3f_values_tag 2
#define pbrt_protobuf_ParamSet_ItemPoint2f_name_tag 1
#define pbrt_protobuf_ParamSet_ItemPoint2f_values_tag 2
#define pbrt_protobuf_ParamSet_ItemPoint3f_name_tag 1
#define pbrt_protobuf_ParamSet_ItemPoint3f_values_tag 2
#define pbrt_protobuf_ParamSet_ItemSpectrum_name_tag 1
#define pbrt_protobuf_ParamSet_ItemSpectrum_values_tag 2
#define pbrt_protobuf_ParamSet_ItemString_name_tag 1
#define pbrt_protobuf_ParamSet_ItemString_values_tag 2
#define pbrt_protobuf_ParamSet_ItemVector2f_name_tag 1
#define pbrt_protobuf_ParamSet_ItemVector2f_values_tag 2
#define pbrt_protobuf_ParamSet_ItemVector3f_name_tag 1
#define pbrt_protobuf_ParamSet_ItemVector3f_values_tag 2
#define pbrt_protobuf_RGBSpectrum_c_tag          1
#define pbrt_protobuf_AnimatedTransform_start_transform_tag 1
#define pbrt_protobuf_AnimatedTransform_end_transform_tag 2
#define pbrt_protobuf_AnimatedTransform_start_time_tag 3
#define pbrt_protobuf_AnimatedTransform_end_time_tag 4
#define pbrt_protobuf_Camera_Film_Filter_name_tag 1
#define pbrt_protobuf_Camera_Film_Filter_paramset_tag 2
#define pbrt_protobuf_Light_name_tag             1
#define pbrt_protobuf_Light_paramset_tag         2
#define pbrt_protobuf_Light_light_to_world_tag   3
#define pbrt_protobuf_Normal3f_x_tag             1
#define pbrt_protobuf_Normal3f_y_tag             2
#define pbrt_protobuf_Normal3f_z_tag             3
#define pbrt_protobuf_ObjectKey_type_tag         1
#define pbrt_protobuf_ObjectKey_id_tag           2
#define pbrt_protobuf_Point2f_x_tag              1
#define pbrt_protobuf_Point2f_y_tag              2
#define pbrt_protobuf_Point2i_x_tag              1
#define pbrt_protobuf_Point2i_y_tag              2
#define pbrt_protobuf_Point3f_x_tag              1
#define pbrt_protobuf_Point3f_y_tag              2
#define pbrt_protobuf_Point3f_z_tag              3
#define pbrt_protobuf_TextureParams_geom_params_tag 1
#define pbrt_protobuf_TextureParams_material_params_tag 2
#define pbrt_protobuf_TextureParams_float_textures_tag 3
#define pbrt_protobuf_TextureParams_spectrum_textures_tag 4
#define pbrt_protobuf_TextureParams_FloatTexturesEntry_key_tag 1
#define pbrt_protobuf_TextureParams_FloatTexturesEntry_value_tag 2
#define pbrt_protobuf_TextureParams_SpectrumTexturesEntry_key_tag 1
#define pbrt_protobuf_TextureParams_SpectrumTexturesEntry_value_tag 2
#define pbrt_protobuf_Triangle_mesh_id_tag       1
#define pbrt_protobuf_Triangle_tri_number_tag    2
#define pbrt_protobuf_TriangleMesh_n_triangles_tag 1
#define pbrt_protobuf_TriangleMesh_n_vertices_tag 2
#define pbrt_protobuf_TriangleMesh_vertex_indices_tag 3
#define pbrt_protobuf_TriangleMesh_p_tag         4
#define pbrt_protobuf_TriangleMesh_n_tag         5
#define pbrt_protobuf_TriangleMesh_s_tag         6
#define pbrt_protobuf_TriangleMesh_uv_tag        7
#define pbrt_protobuf_TriangleMesh_material_id_tag 8
#define pbrt_protobuf_TriangleMesh_id_tag        9
#define pbrt_protobuf_Vector2f_x_tag             1
#define pbrt_protobuf_Vector2f_y_tag             2
#define pbrt_protobuf_Vector3f_x_tag             1
#define pbrt_protobuf_Vector3f_y_tag             2
#define pbrt_protobuf_Vector3f_z_tag             3
#define pbrt_protobuf_Bounds2f_point_min_tag     1
#define pbrt_protobuf_Bounds2f_point_max_tag     2
#define pbrt_protobuf_Bounds2i_point_min_tag     1
#define pbrt_protobuf_Bounds2i_point_max_tag     2
#define pbrt_protobuf_Bounds3f_point_min_tag     1
#define pbrt_protobuf_Bounds3f_point_max_tag     2
#define pbrt_protobuf_Camera_Film_name_tag       1
#define pbrt_protobuf_Camera_Film_paramset_tag   2
#define pbrt_protobuf_Camera_Film_filter_tag     3
#define pbrt_protobuf_FloatTexture_name_tag      1
#define pbrt_protobuf_FloatTexture_tex2world_tag 2
#define pbrt_protobuf_FloatTexture_texture_params_tag 3
#define pbrt_protobuf_Manifest_Object_id_tag     1
#define pbrt_protobuf_Manifest_Object_dependencies_tag 2
#define pbrt_protobuf_Manifest_Object_size_tag   3
#define pbrt_protobuf_Material_name_tag          1
#define pbrt_protobuf_Material_texture_params_tag 2
#define pbrt_protobuf_SampleData_p_film_tag      1
#define pbrt_protobuf_SampleData_weight_tag      2
#define pbrt_protobuf_SpectrumTexture_name_tag   1
#define pbrt_protobuf_SpectrumTexture_tex2world_tag 2
#define pbrt_protobuf_SpectrumTexture_texture_params_tag 3
#define pbrt_protobuf_TransformedPrimitive_transform_tag 1
#define pbrt_protobuf_TransformedPrimitive_root_ref_tag 2
#define pbrt_protobuf_BVHNode_bounds_tag         1
#define pbrt_protobuf_BVHNode_left_ref_tag       2
#define pbrt_protobuf_BVHNode_right_ref_tag      3
#define pbrt_protobuf_BVHNode_axis_tag           4
#define pbrt_protobuf_BVHNode_transformed_primitives_tag 7
#define pbrt_protobuf_BVHNode_triangles_tag      8
#define pbrt_protobuf_Camera_name_tag            1
#define pbrt_protobuf_Camera_paramset_tag        2
#define pbrt_protobuf_Camera_camera_to_world_tag 3
#define pbrt_protobuf_Camera_film_tag            6
#define pbrt_protobuf_Sampler_name_tag           1
#define pbrt_protobuf_Sampler_paramset_tag       2
#define pbrt_protobuf_Sampler_sample_bounds_tag  3
#define pbrt_protobuf_Scene_world_bound_tag      1

/* Struct field encoding specification for nanopb */
#define pbrt_protobuf_Point2f_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2)
#define pbrt_protobuf_Point2f_CALLBACK NULL
#define pbrt_protobuf_Point2f_DEFAULT NULL

#define pbrt_protobuf_Point2i_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    x,                 1) \
X(a, STATIC,   SINGULAR, INT32,    y,                 2)
#define pbrt_protobuf_Point2i_CALLBACK NULL
#define pbrt_protobuf_Point2i_DEFAULT NULL

#define pbrt_protobuf_Point3f_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define pbrt_protobuf_Point3f_CALLBACK NULL
#define pbrt_protobuf_Point3f_DEFAULT NULL

#define pbrt_protobuf_Vector2f_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2)
#define pbrt_protobuf_Vector2f_CALLBACK NULL
#define pbrt_protobuf_Vector2f_DEFAULT NULL

#define pbrt_protobuf_Vector3f_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define pbrt_protobuf_Vector3f_CALLBACK NULL
#define pbrt_protobuf_Vector3f_DEFAULT NULL

#define pbrt_protobuf_Normal3f_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define pbrt_protobuf_Normal3f_CALLBACK NULL
#define pbrt_protobuf_Normal3f_DEFAULT NULL

#define pbrt_protobuf_Matrix_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FLOAT,    m,                 1)
#define pbrt_protobuf_Matrix_CALLBACK pb_default_field_callback
#define pbrt_protobuf_Matrix_DEFAULT NULL

#define pbrt_protobuf_AnimatedTransform_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  start_transform,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  end_transform,     2) \
X(a, STATIC,   SINGULAR, FLOAT,    start_time,        3) \
X(a, STATIC,   SINGULAR, FLOAT,    end_time,          4)
#define pbrt_protobuf_AnimatedTransform_CALLBACK NULL
#define pbrt_protobuf_AnimatedTransform_DEFAULT NULL
#define pbrt_protobuf_AnimatedTransform_start_transform_MSGTYPE pbrt_protobuf_Matrix
#define pbrt_protobuf_AnimatedTransform_end_transform_MSGTYPE pbrt_protobuf_Matrix

#define pbrt_protobuf_Bounds2i_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  point_min,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  point_max,         2)
#define pbrt_protobuf_Bounds2i_CALLBACK NULL
#define pbrt_protobuf_Bounds2i_DEFAULT NULL
#define pbrt_protobuf_Bounds2i_point_min_MSGTYPE pbrt_protobuf_Point2i
#define pbrt_protobuf_Bounds2i_point_max_MSGTYPE pbrt_protobuf_Point2i

#define pbrt_protobuf_Bounds2f_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  point_min,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  point_max,         2)
#define pbrt_protobuf_Bounds2f_CALLBACK NULL
#define pbrt_protobuf_Bounds2f_DEFAULT NULL
#define pbrt_protobuf_Bounds2f_point_min_MSGTYPE pbrt_protobuf_Point2f
#define pbrt_protobuf_Bounds2f_point_max_MSGTYPE pbrt_protobuf_Point2f

#define pbrt_protobuf_Bounds3f_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  point_min,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  point_max,         2)
#define pbrt_protobuf_Bounds3f_CALLBACK NULL
#define pbrt_protobuf_Bounds3f_DEFAULT NULL
#define pbrt_protobuf_Bounds3f_point_min_MSGTYPE pbrt_protobuf_Point3f
#define pbrt_protobuf_Bounds3f_point_max_MSGTYPE pbrt_protobuf_Point3f

#define pbrt_protobuf_TransformedPrimitive_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transform,         1) \
X(a, STATIC,   SINGULAR, INT64,    root_ref,          2)
#define pbrt_protobuf_TransformedPrimitive_CALLBACK NULL
#define pbrt_protobuf_TransformedPrimitive_DEFAULT NULL
#define pbrt_protobuf_TransformedPrimitive_transform_MSGTYPE pbrt_protobuf_AnimatedTransform

#define pbrt_protobuf_TriangleMesh_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    n_triangles,       1) \
X(a, STATIC,   SINGULAR, INT32,    n_vertices,        2) \
X(a, CALLBACK, REPEATED, INT32,    vertex_indices,    3) \
X(a, CALLBACK, REPEATED, MESSAGE,  p,                 4) \
X(a, CALLBACK, REPEATED, MESSAGE,  n,                 5) \
X(a, CALLBACK, REPEATED, MESSAGE,  s,                 6) \
X(a, CALLBACK, REPEATED, MESSAGE,  uv,                7) \
X(a, STATIC,   SINGULAR, INT64,    material_id,       8) \
X(a, STATIC,   SINGULAR, INT64,    id,                9)
#define pbrt_protobuf_TriangleMesh_CALLBACK pb_default_field_callback
#define pbrt_protobuf_TriangleMesh_DEFAULT NULL
#define pbrt_protobuf_TriangleMesh_p_MSGTYPE pbrt_protobuf_Point3f
#define pbrt_protobuf_TriangleMesh_n_MSGTYPE pbrt_protobuf_Normal3f
#define pbrt_protobuf_TriangleMesh_s_MSGTYPE pbrt_protobuf_Vector3f
#define pbrt_protobuf_TriangleMesh_uv_MSGTYPE pbrt_protobuf_Point2f

#define pbrt_protobuf_Triangle_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    mesh_id,           1) \
X(a, STATIC,   SINGULAR, INT64,    tri_number,        2)
#define pbrt_protobuf_Triangle_CALLBACK NULL
#define pbrt_protobuf_Triangle_DEFAULT NULL

#define pbrt_protobuf_BVHNode_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bounds,            1) \
X(a, STATIC,   SINGULAR, INT64,    left_ref,          2) \
X(a, STATIC,   SINGULAR, INT64,    right_ref,         3) \
X(a, STATIC,   SINGULAR, UINT32,   axis,              4) \
X(a, CALLBACK, REPEATED, MESSAGE,  transformed_primitives,   7) \
X(a, CALLBACK, REPEATED, MESSAGE,  triangles,         8)
#define pbrt_protobuf_BVHNode_CALLBACK pb_default_field_callback
#define pbrt_protobuf_BVHNode_DEFAULT NULL
#define pbrt_protobuf_BVHNode_bounds_MSGTYPE pbrt_protobuf_Bounds3f
#define pbrt_protobuf_BVHNode_transformed_primitives_MSGTYPE pbrt_protobuf_TransformedPrimitive
#define pbrt_protobuf_BVHNode_triangles_MSGTYPE pbrt_protobuf_Triangle

#define pbrt_protobuf_RGBSpectrum_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FLOAT,    c,                 1)
#define pbrt_protobuf_RGBSpectrum_CALLBACK pb_default_field_callback
#define pbrt_protobuf_RGBSpectrum_DEFAULT NULL

#define pbrt_protobuf_ParamSet_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  bools,             1) \
X(a, CALLBACK, REPEATED, MESSAGE,  ints,              2) \
X(a, CALLBACK, REPEATED, MESSAGE,  floats,            3) \
X(a, CALLBACK, REPEATED, MESSAGE,  point2fs,          4) \
X(a, CALLBACK, REPEATED, MESSAGE,  vector2fs,         5) \
X(a, CALLBACK, REPEATED, MESSAGE,  point3fs,          6) \
X(a, CALLBACK, REPEATED, MESSAGE,  vector3fs,         7) \
X(a, CALLBACK, REPEATED, MESSAGE,  normals,           8) \
X(a, CALLBACK, REPEATED, MESSAGE,  spectra,           9) \
X(a, CALLBACK, REPEATED, MESSAGE,  strings,          10) \
X(a, CALLBACK, REPEATED, MESSAGE,  textures,         11)
#define pbrt_protobuf_ParamSet_CALLBACK pb_default_field_callback
#define pbrt_protobuf_ParamSet_DEFAULT NULL
#define pbrt_protobuf_ParamSet_bools_MSGTYPE pbrt_protobuf_ParamSet_ItemBool
#define pbrt_protobuf_ParamSet_ints_MSGTYPE pbrt_protobuf_ParamSet_ItemInt
#define pbrt_protobuf_ParamSet_floats_MSGTYPE pbrt_protobuf_ParamSet_ItemFloat
#define pbrt_protobuf_ParamSet_point2fs_MSGTYPE pbrt_protobuf_ParamSet_ItemPoint2f
#define pbrt_protobuf_ParamSet_vector2fs_MSGTYPE pbrt_protobuf_ParamSet_ItemVector2f
#define pbrt_protobuf_ParamSet_point3fs_MSGTYPE pbrt_protobuf_ParamSet_ItemPoint3f
#define pbrt_protobuf_ParamSet_vector3fs_MSGTYPE pbrt_protobuf_ParamSet_ItemVector3f
#define pbrt_protobuf_ParamSet_normals_MSGTYPE pbrt_protobuf_ParamSet_ItemNormal3f
#define pbrt_protobuf_ParamSet_spectra_MSGTYPE pbrt_protobuf_ParamSet_ItemSpectrum
#define pbrt_protobuf_ParamSet_strings_MSGTYPE pbrt_protobuf_ParamSet_ItemString
#define pbrt_protobuf_ParamSet_textures_MSGTYPE pbrt_protobuf_ParamSet_ItemString

#define pbrt_protobuf_ParamSet_ItemBool_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, BOOL,     values,            2)
#define pbrt_protobuf_ParamSet_ItemBool_CALLBACK pb_default_field_callback
#define pbrt_protobuf_ParamSet_ItemBool_DEFAULT NULL

#define pbrt_protobuf_ParamSet_ItemInt_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, INT32,    values,            2)
#define pbrt_protobuf_ParamSet_ItemInt_CALLBACK pb_default_field_callback
#define pbrt_protobuf_ParamSet_ItemInt_DEFAULT NULL

#define pbrt_protobuf_ParamSet_ItemFloat_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, FLOAT,    values,            2)
#define pbrt_protobuf_ParamSet_ItemFloat_CALLBACK pb_default_field_callback
#define pbrt_protobuf_ParamSet_ItemFloat_DEFAULT NULL

#define pbrt_protobuf_ParamSet_ItemPoint2f_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            2)
#define pbrt_protobuf_ParamSet_ItemPoint2f_CALLBACK pb_default_field_callback
#define pbrt_protobuf_ParamSet_ItemPoint2f_DEFAULT NULL
#define pbrt_protobuf_ParamSet_ItemPoint2f_values_MSGTYPE pbrt_protobuf_Point2f

#define pbrt_protobuf_ParamSet_ItemVector2f_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            2)
#define pbrt_protobuf_ParamSet_ItemVector2f_CALLBACK pb_default_field_callback
#define pbrt_protobuf_ParamSet_ItemVector2f_DEFAULT NULL
#define pbrt_protobuf_ParamSet_ItemVector2f_values_MSGTYPE pbrt_protobuf_Vector2f

#define pbrt_protobuf_ParamSet_ItemPoint3f_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            2)
#define pbrt_protobuf_ParamSet_ItemPoint3f_CALLBACK pb_default_field_callback
#define pbrt_protobuf_ParamSet_ItemPoint3f_DEFAULT NULL
#define pbrt_protobuf_ParamSet_ItemPoint3f_values_MSGTYPE pbrt_protobuf_Point3f

#define pbrt_protobuf_ParamSet_ItemVector3f_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            2)
#define pbrt_protobuf_ParamSet_ItemVector3f_CALLBACK pb_default_field_callback
#define pbrt_protobuf_ParamSet_ItemVector3f_DEFAULT NULL
#define pbrt_protobuf_ParamSet_ItemVector3f_values_MSGTYPE pbrt_protobuf_Vector3f

#define pbrt_protobuf_ParamSet_ItemNormal3f_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            2)
#define pbrt_protobuf_ParamSet_ItemNormal3f_CALLBACK pb_default_field_callback
#define pbrt_protobuf_ParamSet_ItemNormal3f_DEFAULT NULL
#define pbrt_protobuf_ParamSet_ItemNormal3f_values_MSGTYPE pbrt_protobuf_Normal3f

#define pbrt_protobuf_ParamSet_ItemSpectrum_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            2)
#define pbrt_protobuf_ParamSet_ItemSpectrum_CALLBACK pb_default_field_callback
#define pbrt_protobuf_ParamSet_ItemSpectrum_DEFAULT NULL
#define pbrt_protobuf_ParamSet_ItemSpectrum_values_MSGTYPE pbrt_protobuf_RGBSpectrum

#define pbrt_protobuf_ParamSet_ItemString_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, STRING,   values,            2)
#define pbrt_protobuf_ParamSet_ItemString_CALLBACK pb_default_field_callback
#define pbrt_protobuf_ParamSet_ItemString_DEFAULT NULL

#define pbrt_protobuf_Sampler_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  paramset,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sample_bounds,     3)
#define pbrt_protobuf_Sampler_CALLBACK pb_default_field_callback
#define pbrt_protobuf_Sampler_DEFAULT NULL
#define pbrt_protobuf_Sampler_paramset_MSGTYPE pbrt_protobuf_ParamSet
#define pbrt_protobuf_Sampler_sample_bounds_MSGTYPE pbrt_protobuf_Bounds2i

#define pbrt_protobuf_Light_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  paramset,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  light_to_world,    3)
#define pbrt_protobuf_Light_CALLBACK pb_default_field_callback
#define pbrt_protobuf_Light_DEFAULT NULL
#define pbrt_protobuf_Light_paramset_MSGTYPE pbrt_protobuf_ParamSet
#define pbrt_protobuf_Light_light_to_world_MSGTYPE pbrt_protobuf_Matrix

#define pbrt_protobuf_Camera_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  paramset,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  camera_to_world,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  film,              6)
#define pbrt_protobuf_Camera_CALLBACK pb_default_field_callback
#define pbrt_protobuf_Camera_DEFAULT NULL
#define pbrt_protobuf_Camera_paramset_MSGTYPE pbrt_protobuf_ParamSet
#define pbrt_protobuf_Camera_camera_to_world_MSGTYPE pbrt_protobuf_AnimatedTransform
#define pbrt_protobuf_Camera_film_MSGTYPE pbrt_protobuf_Camera_Film

#define pbrt_protobuf_Camera_Film_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  paramset,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  filter,            3)
#define pbrt_protobuf_Camera_Film_CALLBACK pb_default_field_callback
#define pbrt_protobuf_Camera_Film_DEFAULT NULL
#define pbrt_protobuf_Camera_Film_paramset_MSGTYPE pbrt_protobuf_ParamSet
#define pbrt_protobuf_Camera_Film_filter_MSGTYPE pbrt_protobuf_Camera_Film_Filter

#define pbrt_protobuf_Camera_Film_Filter_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  paramset,          2)
#define pbrt_protobuf_Camera_Film_Filter_CALLBACK pb_default_field_callback
#define pbrt_protobuf_Camera_Film_Filter_DEFAULT NULL
#define pbrt_protobuf_Camera_Film_Filter_paramset_MSGTYPE pbrt_protobuf_ParamSet

#define pbrt_protobuf_SampleData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  p_film,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    weight,            2)
#define pbrt_protobuf_SampleData_CALLBACK NULL
#define pbrt_protobuf_SampleData_DEFAULT NULL
#define pbrt_protobuf_SampleData_p_film_MSGTYPE pbrt_protobuf_Point2f

#define pbrt_protobuf_Scene_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  world_bound,       1)
#define pbrt_protobuf_Scene_CALLBACK NULL
#define pbrt_protobuf_Scene_DEFAULT NULL
#define pbrt_protobuf_Scene_world_bound_MSGTYPE pbrt_protobuf_Bounds3f

#define pbrt_protobuf_ObjectKey_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1) \
X(a, STATIC,   SINGULAR, UINT64,   id,                2)
#define pbrt_protobuf_ObjectKey_CALLBACK NULL
#define pbrt_protobuf_ObjectKey_DEFAULT NULL

#define pbrt_protobuf_TextureParams_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  geom_params,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  material_params,   2) \
X(a, CALLBACK, REPEATED, MESSAGE,  float_textures,    3) \
X(a, CALLBACK, REPEATED, MESSAGE,  spectrum_textures,   4)
#define pbrt_protobuf_TextureParams_CALLBACK pb_default_field_callback
#define pbrt_protobuf_TextureParams_DEFAULT NULL
#define pbrt_protobuf_TextureParams_geom_params_MSGTYPE pbrt_protobuf_ParamSet
#define pbrt_protobuf_TextureParams_material_params_MSGTYPE pbrt_protobuf_ParamSet
#define pbrt_protobuf_TextureParams_float_textures_MSGTYPE pbrt_protobuf_TextureParams_FloatTexturesEntry
#define pbrt_protobuf_TextureParams_spectrum_textures_MSGTYPE pbrt_protobuf_TextureParams_SpectrumTexturesEntry

#define pbrt_protobuf_TextureParams_FloatTexturesEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, INT32,    value,             2)
#define pbrt_protobuf_TextureParams_FloatTexturesEntry_CALLBACK pb_default_field_callback
#define pbrt_protobuf_TextureParams_FloatTexturesEntry_DEFAULT NULL

#define pbrt_protobuf_TextureParams_SpectrumTexturesEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, INT32,    value,             2)
#define pbrt_protobuf_TextureParams_SpectrumTexturesEntry_CALLBACK pb_default_field_callback
#define pbrt_protobuf_TextureParams_SpectrumTexturesEntry_DEFAULT NULL

#define pbrt_protobuf_Material_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  texture_params,    2)
#define pbrt_protobuf_Material_CALLBACK pb_default_field_callback
#define pbrt_protobuf_Material_DEFAULT NULL
#define pbrt_protobuf_Material_texture_params_MSGTYPE pbrt_protobuf_TextureParams

#define pbrt_protobuf_FloatTexture_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tex2world,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  texture_params,    3)
#define pbrt_protobuf_FloatTexture_CALLBACK pb_default_field_callback
#define pbrt_protobuf_FloatTexture_DEFAULT NULL
#define pbrt_protobuf_FloatTexture_tex2world_MSGTYPE pbrt_protobuf_Matrix
#define pbrt_protobuf_FloatTexture_texture_params_MSGTYPE pbrt_protobuf_TextureParams

#define pbrt_protobuf_SpectrumTexture_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tex2world,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  texture_params,    3)
#define pbrt_protobuf_SpectrumTexture_CALLBACK pb_default_field_callback
#define pbrt_protobuf_SpectrumTexture_DEFAULT NULL
#define pbrt_protobuf_SpectrumTexture_tex2world_MSGTYPE pbrt_protobuf_Matrix
#define pbrt_protobuf_SpectrumTexture_texture_params_MSGTYPE pbrt_protobuf_TextureParams

#define pbrt_protobuf_Manifest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  objects,           1)
#define pbrt_protobuf_Manifest_CALLBACK pb_default_field_callback
#define pbrt_protobuf_Manifest_DEFAULT NULL
#define pbrt_protobuf_Manifest_objects_MSGTYPE pbrt_protobuf_Manifest_Object

#define pbrt_protobuf_Manifest_Object_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  id,                1) \
X(a, CALLBACK, REPEATED, MESSAGE,  dependencies,      2) \
X(a, STATIC,   SINGULAR, UINT64,   size,              3)
#define pbrt_protobuf_Manifest_Object_CALLBACK pb_default_field_callback
#define pbrt_protobuf_Manifest_Object_DEFAULT NULL
#define pbrt_protobuf_Manifest_Object_id_MSGTYPE pbrt_protobuf_ObjectKey
#define pbrt_protobuf_Manifest_Object_dependencies_MSGTYPE pbrt_protobuf_ObjectKey

extern const pb_msgdesc_t pbrt_protobuf_Point2f_msg;
extern const pb_msgdesc_t pbrt_protobuf_Point2i_msg;
extern const pb_msgdesc_t pbrt_protobuf_Point3f_msg;
extern const pb_msgdesc_t pbrt_protobuf_Vector2f_msg;
extern const pb_msgdesc_t pbrt_protobuf_Vector3f_msg;
extern const pb_msgdesc_t pbrt_protobuf_Normal3f_msg;
extern const pb_msgdesc_t pbrt_protobuf_Matrix_msg;
extern const pb_msgdesc_t pbrt_protobuf_AnimatedTransform_msg;
extern const pb_msgdesc_t pbrt_protobuf_Bounds2i_msg;
extern const pb_msgdesc_t pbrt_protobuf_Bounds2f_msg;
extern const pb_msgdesc_t pbrt_protobuf_Bounds3f_msg;
extern const pb_msgdesc_t pbrt_protobuf_TransformedPrimitive_msg;
extern const pb_msgdesc_t pbrt_protobuf_TriangleMesh_msg;
extern const pb_msgdesc_t pbrt_protobuf_Triangle_msg;
extern const pb_msgdesc_t pbrt_protobuf_BVHNode_msg;
extern const pb_msgdesc_t pbrt_protobuf_RGBSpectrum_msg;
extern const pb_msgdesc_t pbrt_protobuf_ParamSet_msg;
extern const pb_msgdesc_t pbrt_protobuf_ParamSet_ItemBool_msg;
extern const pb_msgdesc_t pbrt_protobuf_ParamSet_ItemInt_msg;
extern const pb_msgdesc_t pbrt_protobuf_ParamSet_ItemFloat_msg;
extern const pb_msgdesc_t pbrt_protobuf_ParamSet_ItemPoint2f_msg;
extern const pb_msgdesc_t pbrt_protobuf_ParamSet_ItemVector2f_msg;
extern const pb_msgdesc_t pbrt_protobuf_ParamSet_ItemPoint3f_msg;
extern const pb_msgdesc_t pbrt_protobuf_ParamSet_ItemVector3f_msg;
extern const pb_msgdesc_t pbrt_protobuf_ParamSet_ItemNormal3f_msg;
extern const pb_msgdesc_t pbrt_protobuf_ParamSet_ItemSpectrum_msg;
extern const pb_msgdesc_t pbrt_protobuf_ParamSet_ItemString_msg;
extern const pb_msgdesc_t pbrt_protobuf_Sampler_msg;
extern const pb_msgdesc_t pbrt_protobuf_Light_msg;
extern const pb_msgdesc_t pbrt_protobuf_Camera_msg;
extern const pb_msgdesc_t pbrt_protobuf_Camera_Film_msg;
extern const pb_msgdesc_t pbrt_protobuf_Camera_Film_Filter_msg;
extern const pb_msgdesc_t pbrt_protobuf_SampleData_msg;
extern const pb_msgdesc_t pbrt_protobuf_Scene_msg;
extern const pb_msgdesc_t pbrt_protobuf_ObjectKey_msg;
extern const pb_msgdesc_t pbrt_protobuf_TextureParams_msg;
extern const pb_msgdesc_t pbrt_protobuf_TextureParams_FloatTexturesEntry_msg;
extern const pb_msgdesc_t pbrt_protobuf_TextureParams_SpectrumTexturesEntry_msg;
extern const pb_msgdesc_t pbrt_protobuf_Material_msg;
extern const pb_msgdesc_t pbrt_protobuf_FloatTexture_msg;
extern const pb_msgdesc_t pbrt_protobuf_SpectrumTexture_msg;
extern const pb_msgdesc_t pbrt_protobuf_Manifest_msg;
extern const pb_msgdesc_t pbrt_protobuf_Manifest_Object_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pbrt_protobuf_Point2f_fields &pbrt_protobuf_Point2f_msg
#define pbrt_protobuf_Point2i_fields &pbrt_protobuf_Point2i_msg
#define pbrt_protobuf_Point3f_fields &pbrt_protobuf_Point3f_msg
#define pbrt_protobuf_Vector2f_fields &pbrt_protobuf_Vector2f_msg
#define pbrt_protobuf_Vector3f_fields &pbrt_protobuf_Vector3f_msg
#define pbrt_protobuf_Normal3f_fields &pbrt_protobuf_Normal3f_msg
#define pbrt_protobuf_Matrix_fields &pbrt_protobuf_Matrix_msg
#define pbrt_protobuf_AnimatedTransform_fields &pbrt_protobuf_AnimatedTransform_msg
#define pbrt_protobuf_Bounds2i_fields &pbrt_protobuf_Bounds2i_msg
#define pbrt_protobuf_Bounds2f_fields &pbrt_protobuf_Bounds2f_msg
#define pbrt_protobuf_Bounds3f_fields &pbrt_protobuf_Bounds3f_msg
#define pbrt_protobuf_TransformedPrimitive_fields &pbrt_protobuf_TransformedPrimitive_msg
#define pbrt_protobuf_TriangleMesh_fields &pbrt_protobuf_TriangleMesh_msg
#define pbrt_protobuf_Triangle_fields &pbrt_protobuf_Triangle_msg
#define pbrt_protobuf_BVHNode_fields &pbrt_protobuf_BVHNode_msg
#define pbrt_protobuf_RGBSpectrum_fields &pbrt_protobuf_RGBSpectrum_msg
#define pbrt_protobuf_ParamSet_fields &pbrt_protobuf_ParamSet_msg
#define pbrt_protobuf_ParamSet_ItemBool_fields &pbrt_protobuf_ParamSet_ItemBool_msg
#define pbrt_protobuf_ParamSet_ItemInt_fields &pbrt_protobuf_ParamSet_ItemInt_msg
#define pbrt_protobuf_ParamSet_ItemFloat_fields &pbrt_protobuf_ParamSet_ItemFloat_msg
#define pbrt_protobuf_ParamSet_ItemPoint2f_fields &pbrt_protobuf_ParamSet_ItemPoint2f_msg
#define pbrt_protobuf_ParamSet_ItemVector2f_fields &pbrt_protobuf_ParamSet_ItemVector2f_msg
#define pbrt_protobuf_ParamSet_ItemPoint3f_fields &pbrt_protobuf_ParamSet_ItemPoint3f_msg
#define pbrt_protobuf_ParamSet_ItemVector3f_fields &pbrt_protobuf_ParamSet_ItemVector3f_msg
#define pbrt_protobuf_ParamSet_ItemNormal3f_fields &pbrt_protobuf_ParamSet_ItemNormal3f_msg
#define pbrt_protobuf_ParamSet_ItemSpectrum_fields &pbrt_protobuf_ParamSet_ItemSpectrum_msg
#define pbrt_protobuf_ParamSet_ItemString_fields &pbrt_protobuf_ParamSet_ItemString_msg
#define pbrt_protobuf_Sampler_fields &pbrt_protobuf_Sampler_msg
#define pbrt_protobuf_Light_fields &pbrt_protobuf_Light_msg
#define pbrt_protobuf_Camera_fields &pbrt_protobuf_Camera_msg
#define pbrt_protobuf_Camera_Film_fields &pbrt_protobuf_Camera_Film_msg
#define pbrt_protobuf_Camera_Film_Filter_fields &pbrt_protobuf_Camera_Film_Filter_msg
#define pbrt_protobuf_SampleData_fields &pbrt_protobuf_SampleData_msg
#define pbrt_protobuf_Scene_fields &pbrt_protobuf_Scene_msg
#define pbrt_protobuf_ObjectKey_fields &pbrt_protobuf_ObjectKey_msg
#define pbrt_protobuf_TextureParams_fields &pbrt_protobuf_TextureParams_msg
#define pbrt_protobuf_TextureParams_FloatTexturesEntry_fields &pbrt_protobuf_TextureParams_FloatTexturesEntry_msg
#define pbrt_protobuf_TextureParams_SpectrumTexturesEntry_fields &pbrt_protobuf_TextureParams_SpectrumTexturesEntry_msg
#define pbrt_protobuf_Material_fields &pbrt_protobuf_Material_msg
#define pbrt_protobuf_FloatTexture_fields &pbrt_protobuf_FloatTexture_msg
#define pbrt_protobuf_SpectrumTexture_fields &pbrt_protobuf_SpectrumTexture_msg
#define pbrt_protobuf_Manifest_fields &pbrt_protobuf_Manifest_msg
#define pbrt_protobuf_Manifest_Object_fields &pbrt_protobuf_Manifest_Object_msg

/* Maximum encoded size of messages (where known) */
#define pbrt_protobuf_Point2f_size               10
#define pbrt_protobuf_Point2i_size               22
#define pbrt_protobuf_Point3f_size               15
#define pbrt_protobuf_Vector2f_size              10
#define pbrt_protobuf_Vector3f_size              15
#define pbrt_protobuf_Normal3f_size              15
/* pbrt_protobuf_Matrix_size depends on runtime parameters */
/* pbrt_protobuf_AnimatedTransform_size depends on runtime parameters */
#define pbrt_protobuf_Bounds2i_size              48
#define pbrt_protobuf_Bounds2f_size              24
#define pbrt_protobuf_Bounds3f_size              34
/* pbrt_protobuf_TransformedPrimitive_size depends on runtime parameters */
/* pbrt_protobuf_TriangleMesh_size depends on runtime parameters */
#define pbrt_protobuf_Triangle_size              22
/* pbrt_protobuf_BVHNode_size depends on runtime parameters */
/* pbrt_protobuf_RGBSpectrum_size depends on runtime parameters */
/* pbrt_protobuf_ParamSet_size depends on runtime parameters */
/* pbrt_protobuf_ParamSet_ItemBool_size depends on runtime parameters */
/* pbrt_protobuf_ParamSet_ItemInt_size depends on runtime parameters */
/* pbrt_protobuf_ParamSet_ItemFloat_size depends on runtime parameters */
/* pbrt_protobuf_ParamSet_ItemPoint2f_size depends on runtime parameters */
/* pbrt_protobuf_ParamSet_ItemVector2f_size depends on runtime parameters */
/* pbrt_protobuf_ParamSet_ItemPoint3f_size depends on runtime parameters */
/* pbrt_protobuf_ParamSet_ItemVector3f_size depends on runtime parameters */
/* pbrt_protobuf_ParamSet_ItemNormal3f_size depends on runtime parameters */
/* pbrt_protobuf_ParamSet_ItemSpectrum_size depends on runtime parameters */
/* pbrt_protobuf_ParamSet_ItemString_size depends on runtime parameters */
/* pbrt_protobuf_Sampler_size depends on runtime parameters */
/* pbrt_protobuf_Light_size depends on runtime parameters */
/* pbrt_protobuf_Camera_size depends on runtime parameters */
/* pbrt_protobuf_Camera_Film_size depends on runtime parameters */
/* pbrt_protobuf_Camera_Film_Filter_size depends on runtime parameters */
#define pbrt_protobuf_SampleData_size            17
#define pbrt_protobuf_Scene_size                 36
#define pbrt_protobuf_ObjectKey_size             17
/* pbrt_protobuf_TextureParams_size depends on runtime parameters */
/* pbrt_protobuf_TextureParams_FloatTexturesEntry_size depends on runtime parameters */
/* pbrt_protobuf_TextureParams_SpectrumTexturesEntry_size depends on runtime parameters */
/* pbrt_protobuf_Material_size depends on runtime parameters */
/* pbrt_protobuf_FloatTexture_size depends on runtime parameters */
/* pbrt_protobuf_SpectrumTexture_size depends on runtime parameters */
/* pbrt_protobuf_Manifest_size depends on runtime parameters */
/* pbrt_protobuf_Manifest_Object_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
