/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "pbrt.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pbrt_protobuf_Point2f, pbrt_protobuf_Point2f, AUTO)


PB_BIND(pbrt_protobuf_Point2i, pbrt_protobuf_Point2i, AUTO)


PB_BIND(pbrt_protobuf_Point3f, pbrt_protobuf_Point3f, AUTO)


PB_BIND(pbrt_protobuf_Vector2f, pbrt_protobuf_Vector2f, AUTO)


PB_BIND(pbrt_protobuf_Vector3f, pbrt_protobuf_Vector3f, AUTO)


PB_BIND(pbrt_protobuf_Normal3f, pbrt_protobuf_Normal3f, AUTO)


PB_BIND(pbrt_protobuf_Matrix, pbrt_protobuf_Matrix, AUTO)


PB_BIND(pbrt_protobuf_AnimatedTransform, pbrt_protobuf_AnimatedTransform, AUTO)


PB_BIND(pbrt_protobuf_Bounds2i, pbrt_protobuf_Bounds2i, AUTO)


PB_BIND(pbrt_protobuf_Bounds2f, pbrt_protobuf_Bounds2f, AUTO)


PB_BIND(pbrt_protobuf_Bounds3f, pbrt_protobuf_Bounds3f, AUTO)


PB_BIND(pbrt_protobuf_TransformedPrimitive, pbrt_protobuf_TransformedPrimitive, AUTO)


PB_BIND(pbrt_protobuf_TriangleMesh, pbrt_protobuf_TriangleMesh, AUTO)


PB_BIND(pbrt_protobuf_Triangle, pbrt_protobuf_Triangle, AUTO)


PB_BIND(pbrt_protobuf_BVHNode, pbrt_protobuf_BVHNode, AUTO)


PB_BIND(pbrt_protobuf_RGBSpectrum, pbrt_protobuf_RGBSpectrum, AUTO)


PB_BIND(pbrt_protobuf_ParamSet, pbrt_protobuf_ParamSet, AUTO)


PB_BIND(pbrt_protobuf_ParamSet_ItemBool, pbrt_protobuf_ParamSet_ItemBool, AUTO)


PB_BIND(pbrt_protobuf_ParamSet_ItemInt, pbrt_protobuf_ParamSet_ItemInt, AUTO)


PB_BIND(pbrt_protobuf_ParamSet_ItemFloat, pbrt_protobuf_ParamSet_ItemFloat, AUTO)


PB_BIND(pbrt_protobuf_ParamSet_ItemPoint2f, pbrt_protobuf_ParamSet_ItemPoint2f, AUTO)


PB_BIND(pbrt_protobuf_ParamSet_ItemVector2f, pbrt_protobuf_ParamSet_ItemVector2f, AUTO)


PB_BIND(pbrt_protobuf_ParamSet_ItemPoint3f, pbrt_protobuf_ParamSet_ItemPoint3f, AUTO)


PB_BIND(pbrt_protobuf_ParamSet_ItemVector3f, pbrt_protobuf_ParamSet_ItemVector3f, AUTO)


PB_BIND(pbrt_protobuf_ParamSet_ItemNormal3f, pbrt_protobuf_ParamSet_ItemNormal3f, AUTO)


PB_BIND(pbrt_protobuf_ParamSet_ItemSpectrum, pbrt_protobuf_ParamSet_ItemSpectrum, AUTO)


PB_BIND(pbrt_protobuf_ParamSet_ItemString, pbrt_protobuf_ParamSet_ItemString, AUTO)


PB_BIND(pbrt_protobuf_Sampler, pbrt_protobuf_Sampler, 2)


PB_BIND(pbrt_protobuf_Light, pbrt_protobuf_Light, 2)


PB_BIND(pbrt_protobuf_Camera, pbrt_protobuf_Camera, 2)


PB_BIND(pbrt_protobuf_Camera_Film, pbrt_protobuf_Camera_Film, 2)


PB_BIND(pbrt_protobuf_Camera_Film_Filter, pbrt_protobuf_Camera_Film_Filter, AUTO)


PB_BIND(pbrt_protobuf_SampleData, pbrt_protobuf_SampleData, AUTO)


PB_BIND(pbrt_protobuf_Scene, pbrt_protobuf_Scene, AUTO)


PB_BIND(pbrt_protobuf_ObjectKey, pbrt_protobuf_ObjectKey, AUTO)


PB_BIND(pbrt_protobuf_TextureParams, pbrt_protobuf_TextureParams, 2)


PB_BIND(pbrt_protobuf_TextureParams_FloatTexturesEntry, pbrt_protobuf_TextureParams_FloatTexturesEntry, AUTO)


PB_BIND(pbrt_protobuf_TextureParams_SpectrumTexturesEntry, pbrt_protobuf_TextureParams_SpectrumTexturesEntry, AUTO)


PB_BIND(pbrt_protobuf_Material, pbrt_protobuf_Material, 2)


PB_BIND(pbrt_protobuf_FloatTexture, pbrt_protobuf_FloatTexture, 2)


PB_BIND(pbrt_protobuf_SpectrumTexture, pbrt_protobuf_SpectrumTexture, 2)


PB_BIND(pbrt_protobuf_Manifest, pbrt_protobuf_Manifest, AUTO)


PB_BIND(pbrt_protobuf_Manifest_Object, pbrt_protobuf_Manifest_Object, AUTO)



